version: '3.8'

services:

  db:
    container_name: db
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile.postres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  app:
    depends_on:
      - db
    volumes:
      - '.:/app'
      - '/app/node_modules'
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}?schema=public
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  postgres:
